# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
  repositories:
    - repository: templates
      type: git
      name: Technique.Azure-Pipelines.Templates
      ref: refs/heads/main

trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - develop
    - test
    - main
    - feature/*

pool: 'Linux'

extends:
  template: frontend/backend-azure-template.yaml@templates
  parameters:
    projectKey: "Technique.Frontend "
    projectName: "Technique Frontend"
    repositoryName: "Technique Frontend"
    #containerize: true
    imageName: "technique-frontend"
    ## Where to push ?!
    #containerRegistry: "technique.azurecr.io"
    #containerRegistryServiceName: "Azure Container Registry"
